version: "3.5" 
services:




# ============================================================================
# ============================================================================
#                           SIMPLE PATH PLANNER
# ============================================================================
# ============================================================================
  microservice_trailer_transport:
    build: 
      context: .
      dockerfile: Dockerfile
      target: ${TARGET:-prod}

    container_name: local_planner_service

    ports:
      - "9100:9100"
      - "5681:5681"

    restart: always

    networks:
      - control-tower-net

    volumes:
        - ./:/app

networks:
    control-tower-net:
        name: control-tower-net
        external: true