version: "3.5" 
services:




# ============================================================================
# ============================================================================
#                           SIMPLE PATH PLANNER
# ============================================================================
# ============================================================================
  microservice:
    build: 
      context: .
      dockerfile: Dockerfile
      target: ${TARGET}

    container_name: local_planner_service

    ports:
      - "9000:9000"
      - "5680:5680"

    restart: always

    networks:
      - control-tower-net

    volumes:
        - ./:/app

networks:
    control-tower-net:
        name: control-tower-net
        external: true